config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :posts
  end

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :find_user, only: [:new, :create, :edit, :update, :destroy]
  
    # GET /posts
    def index
      @posts = current_user.posts
    end
  
    # GET /posts/1
    def show
    end
  
    # GET /posts/new
    def new
      @post = Post.new
    end
  
    # GET /posts/1/edit
    def edit
      if @post.user != current_user
        redirect_to user_posts_path, alert: "You do not have permission to edit this post."
      end
    end
  
    # POST /posts
    def create
      @post = Post.new(post_params)
      @post.user = current_user # assuming you have a current_user method in your application
  
      if @post.save
        redirect_to user_posts_path, notice: 'Post was successfully created.'
      else
        render :new
      end
    end
  
    # PATCH/PUT /posts/1
    def update
      if @post.user != current_user
        redirect_to user_posts_path, alert: "You do not have permission to edit this post."
      else
        if @post.update(post_params)
          redirect_to user_post_path(current_user, @post), notice: 'Post was successfully updated.'
        else
          render :edit
        end
      end
    end
  
    # DELETE /posts/1
    def destroy
         @post.destroy
        redirect_to user_posts_path, notice: 'Post was successfully destroyed.'
            
    end
  
    private

    def find_user
        @user = current_user
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :price, :year, :km, :region, :post_status, :user_id)
    end
  end
  

app/views/posts/edit.html.erb
<%= simple_form_for [@user, @post] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :year %>
  <%= f.input :km %>
  <%= f.input :region %>
  <%= f.input :post_status %>
  <%= f.button :submit, "Atualizar", class: "btn btn-outline-primary rounded-pill" %>
<% end %>

app/views/posts/index.html.erb
<%= link_to "New", new_user_post_path %>

<% @posts.each do |post| %>
    <p><%= post.title %></p>
    <p><%= post.description %></p>
    <p><%= post.price %></p>
    <p><%= post.year %></p>
    <p><%= post.km %></p>
    <p><%= post.region %></p>
    <p><%= post.post_status %></p>
    <p><%= post.user.email %></p>
    <% if current_user == post.user %>
      <%= link_to "Edit", edit_user_post_path(current_user, post) %>
    <% end %>
    <%= link_to "Show", user_post_path(current_user, post) %>
    <% end %>

app/views/posts/new.html.erb
<%= simple_form_for [@user, @post] do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.input :price %>
  <%= f.input :year %>
  <%= f.input :km %>
  <%= f.input :region %>
  <%= f.input :post_status %>
  <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<h1>POST SHOW</h1>



<div class="card mb-3">
  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="..." class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="..." class="d-block w-100" alt="...">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @post.title %></h5>
    <p class="card-text"><%= @post.description %></p>
    <p class="card-text"><%= @post.price %></p>
    <p class="card-text"><%= @post.year %></p>
    <p class="card-text"><%= @post.km %></p>
    <p class="card-text"><%= @post.region %></p>
    <p class="card-text"><%= @post.post_status %></p>
    <p class="card-text"><%= @post.user.contact %></p>
    <p class="card-text"><small class="text-body-secondary"><%= @post.updated_at %></small></p>
  </div>
</div>

<% if current_user == @post.user %>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-outline-danger rounded-pill" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Apagar
  </button>
  <%= link_to "Editar", edit_user_post_path(current_user), class: "btn btn-outline-info rounded-pill" %>

  <!-- Modal to Delete -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">APAGAR?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Uma vez apagado o post não poderá ser recuperado.
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
        <%= link_to "Confirmar", user_post_path(current_user, @post), method: :delete, data: { turbo_method: :delete }, class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>
<% end %>